version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'


  db:
    image: postgres
    env_file:
      - .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A DRFhw_1 worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - redis
      - app
  celery_beat:
    build: .
    tty: true
    command: celery -A DRFhw_1 beat -l INFO -S django
    volumes:
      - .:/code
    depends_on:
      - redis
      - app
volumes:
  pg_data:
