# Generated by Django 4.2.6 on 2023-11-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_lesson'),
        ('lesson', '0004_lesson_course'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payday',
            field=models.DateField(blank=True, null=True, verbose_name='payday'),
        ),
    ]
