# Generated by Django 4.2.6 on 2023-11-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_course_alter_payment_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'наличные'), ('card', 'перевод')], default='cash', verbose_name='method'),
        ),
    ]
