# Generated by Django 4.2.6 on 2023-10-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
